server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  datasource:
    url: jdbc:mariadb://localhost:3306/registration
    username: root
    password: james2

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format-sql: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: eco.ride.germany@gmail.com
    password: srpyyfidibekflju
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
            auth: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
