name: Docker Image CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag matrex:latest

    - name: Run the Docker image
      run: docker run matrex:latest
