name: Run Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/mizoo1/eco-ride:latest
        env:
          SETUP_BUILDX: ${{ steps.setup_buildx.outputs.name }}

      - name: Run Docker container
        run: |
          docker run ghcr.io/mizoo1/eco-ride:latest
